FROM python:3.12-slim

WORKDIR /tests
COPY tests /tests/tests

RUN pip install --no-cache-dir \
    pytest==8.3.2 \
    requests==2.32.3 \
    psycopg[binary]==3.2.1 \
    allure-pytest==2.13.5

CMD ["pytest", "-q", "tests/api"]
